name: "Junie GH Action v1.0"
description: "Powerful GitHub automation with Junie."
branding:
  icon: "at-sign"
  color: "green"

inputs:
  trigger_phrase:
    description: "The trigger phrase to look for in comments or issue body"
    required: false
    default: "@junie"
  assignee_trigger:
    description: "The assignee username that triggers the action (e.g. @junie)"
    required: false
  label_trigger:
    description: "The label that triggers the action (e.g. junie)"
    required: false
    default: "junie"
  base_branch:
    description: "The branch to use as the source when creating junie working branch"
    required: false

  # Junie configuration
  prompt:
    description: "Instructions for Junie. Can be a direct prompt or custom template."
    required: false
    default: ""
  junie_version:
    description: "Version of Junie to use"
    required: false
    default: "443.1"
  junie_work_dir:
    description: "Directory to use for Junie working files"
    required: false
    default: "/tmp/junie-work"

  # Auth configuration
  junie_api_key:
    description: "Junie API key"
    required: false
  github_token:
    description: "GitHub token with repo and pull request permissions (optional if using GitHub App)"
    required: false

outputs:
  branch_name:
    description: "Junie working branch"
    value: ${{ steps.prepare.outputs.EJ_WORKING_BRANCH }}

runs:
  using: "composite"
  steps:
    - name: Install Bun
      if: inputs.path_to_bun_executable == ''
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Prepare action
      id: prepare
      shell: bash
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoints/prepare.ts
      env:
        APP_TOKEN: ${{ inputs.junie_api_key }}
        PROMPT: ${{ inputs.prompt }}
        TRIGGER_PHRASE: ${{ inputs.trigger_phrase }}
        ASSIGNEE_TRIGGER: ${{ inputs.assignee_trigger }}
        LABEL_TRIGGER: ${{ inputs.label_trigger }}
        BASE_BRANCH: ${{ inputs.base_branch || github.base_ref  }}
        TARGET_BRANCH: ${{ github.head_ref }}
        OVERRIDE_GITHUB_TOKEN: ${{ inputs.github_token }}
        DEFAULT_WORKFLOW_TOKEN: ${{ github.token }}
        ALL_INPUTS: ${{ toJson(inputs) }}

    - name: Install Junie
      if: steps.prepare.outputs.SHOULD_SKIP != 'true'
      shell: bash
      run: npm install -g @jetbrains/junie-cli

    - name: Run Junie
      if: steps.prepare.outputs.SHOULD_SKIP != 'true'
      shell: bash
      id: junie-run
      env:
        CLI_TOKEN: ${{ steps.prepare.outputs.EJ_CLI_TOKEN }}
        EJ_TASK: ${{ steps.prepare.outputs.EJ_TASK }}
        EJ_AUTH_GITHUB_TOKEN: ${{ steps.prepare.outputs.EJ_AUTH_GITHUB_TOKEN  }}
        EJ_TASK_TEXT: ${{ steps.prepare.outputs.EJ_TASK_TEXT }}
        MULTI_RUNS: true
        MATTERHORN_DEBUG_LOG: false
        WORKING_DIR: ${{ inputs.junie_work_dir }}
      run: |
        OUTPUT=$(junie --cache-dir="${WORKING_DIR}" --output-format="json" --auth="${CLI_TOKEN}" "${EJ_TASK}")
        echo "json_output<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Handle Junie results
      if: steps.prepare.outputs.SHOULD_SKIP != 'true'
      shell: bash
      id: junie-run-results
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoints/handle-results.ts
      env:
        JSON_JUNIE_OUTPUT: ${{ steps.junie-run.outputs.json_output }}
        PREPARE_OUTPUT: ${{ steps.prepare.outputs.PREPARE_OUTPUT }}
        WORKING_DIR: ${{ inputs.junie_work_dir }}

    - name: Upload Junie working directory as artifact
      if: always() && steps.prepare.outputs.SHOULD_SKIP != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: junie-working-directory
        path: ${{ inputs.junie_work_dir }}
        retention-days: 7
        if-no-files-found: warn
        include-hidden-files: true

    - name: Make Pull Request for the changes
      if: steps.prepare.outputs.SHOULD_SKIP != 'true' && steps.junie-run-results.outputs.CREATE_PR == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
          token: ${{ steps.prepare.outputs.EJ_AUTH_GITHUB_TOKEN }}
          commit-message: ${{ steps.junie-run-results.outputs.COMMIT_MESSAGE }}
          title: ${{ steps.junie-run-results.outputs.PR_TITLE }}
          body: ${{ steps.junie-run-results.outputs.PR_BODY }}
          branch: ${{ steps.prepare.outputs.EJ_WORKING_BRANCH }}
          base: ${{ steps.prepare.outputs.EJ_BASE_BRANCH }}

    - uses: EndBug/add-and-commit@v9
      name: Commit changes
      if: steps.prepare.outputs.SHOULD_SKIP != 'true' && steps.junie-run-results.outputs.CREATE_PR == 'false'
      with:
        author_name: ${{ steps.prepare.outputs.EJ_ACTOR_NAME }}
        author_email: ${{ steps.prepare.outputs.EJ_ACTOR_EMAIL }}
        new_branch: ${{ steps.prepare.outputs.EJ_WORKING_BRANCH }}
        message: ${{ steps.junie-run-results.outputs.COMMIT_MESSAGE }}
