name: analyze-failed-checks.yml
on:
  workflow_run:
    workflows: ["Test that always fails"]
    types: [completed]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump workflow_run event
        run: |
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "PR array length: ${{ github.event.workflow_run.event }}"
          echo "Full event payload:"
          echo "${{ toJSON(github.event.workflow_run) }}"
  junie:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Junie
        id: claude
        uses: ./.
        with:
          junie_api_key: ${{ secrets.JUNIE_API_KEY }}
          prompt: |
            You are working on branch ${{ github.event.workflow_run.pull_requests[0].head.ref }}.
            The user makes changes against the branch ${{ github.event.workflow_run.pull_requests[0].base.ref }} and this make a CI checks fails:
            
            Use mcp_github_checks_server to get derailed information about the failed checks.
